@HelloTeam.Api_HostAddress = http://localhost:11130

GET {{HelloTeam.Api_HostAddress}}/api/hello
Accept: application/json

###

GET {{HelloTeam.Api_HostAddress}}/health/live
Accept: application/json

###

GET {{HelloTeam.Api_HostAddress}}/health/ready
Accept: application/json
