apiVersion: v1
kind: Pod
metadata:
  name: load-generator
spec:
  containers:
    - name: load-generator
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - while true; do wget -q -O- http://webapi:11130/api/hello; done
  restartPolicy: Never
