apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp

spec:
  replicas: 2

  selector:
    matchLabels:
      app: webapp

  template:
    metadata:
      labels:
        app: webapp

    spec:
      containers:
        - name: webapp
          image: ghcr.io/ahmetakca11086/hello-team-web:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 52369

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"