name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_API: ghcr.io/${{ github.repository_owner }}/hello-team-api
  IMAGE_WEB: ghcr.io/${{ github.repository_owner }}/hello-team-web

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout
        uses: actions/checkout@v4

      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      
      - name: Restore
        run: dotnet restore HelloTeam.sln

      
      - name: Build
        run: dotnet build HelloTeam.sln --configuration Release --no-restore

      
      - name: Test
        run: dotnet test HelloTeam.sln --configuration Release --no-build

      
      - name: Login to GHCR
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      
      - name: Build & Push API
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/HelloTeam.Api/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.IMAGE_API }}:${{ github.sha }}
            ${{ env.IMAGE_API }}:latest

    
      - name: Build & Push Web
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/HelloTeam.Web/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.IMAGE_WEB }}:${{ github.sha }}
            ${{ env.IMAGE_WEB }}:latest

      - name: Set kubeconfig
        if: github.ref == 'refs/heads/main'
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      
      - name: Deploy API
        if: github.ref == 'refs/heads/main'
        run: |
          kubectl set image deployment/hello-team-api \
            api=${{ env.IMAGE_API }}:${{ github.sha }}

          kubectl rollout status deployment/hello-team-api

      
      - name: Deploy Web
        if: github.ref == 'refs/heads/main'
        run: |
          kubectl set image deployment/webapp \
            web=${{ env.IMAGE_WEB }}:${{ github.sha }}

          kubectl rollout status deployment/webapp